import fs from 'node:fs';
import path from 'node:path';
import { CookieJar } from 'tough-cookie';
import { NicoAuthCookieName } from '@shared/constants';
import { createLogger } from '../../util/Logger';

const log = createLogger('CookieStore');

/**
 * tough-cookie の CookieJar をファイルにシリアライズして永続化する。
 *
 * 元のNNDD/AIRでは EncryptedLocalStore に保存していたが、
 * Electron では `app.getPath('userData')` 配下に JSON で保存する。
 * (将来 safeStorage で暗号化する余地を残す)
 */
export class CookieStore {
  private jar: CookieJar;

  private constructor(
    jar: CookieJar,
    private readonly filePath: string
  ) {
    this.jar = jar;
  }

  static async load(filePath: string): Promise<CookieStore> {
    let jar: CookieJar;
    if (fs.existsSync(filePath)) {
      try {
        const raw = fs.readFileSync(filePath, 'utf-8');
        jar = await CookieJar.deserialize(JSON.parse(raw));
        log.verbose('Cookie jar loaded:', filePath);
      } catch (e) {
        log.warn('Failed to load cookie jar, creating new one:', e);
        jar = new CookieJar();
      }
    } else {
      jar = new CookieJar();
    }
    return new CookieStore(jar, filePath);
  }

  /** Jar をJSON化して保存 */
  async save(): Promise<void> {
    const dir = path.dirname(this.filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const serialized = await this.jar.serialize();
    fs.writeFileSync(this.filePath, JSON.stringify(serialized, null, 2), 'utf-8');
  }

  /** 指定URLに送信するCookieヘッダー文字列を組み立てる */
  async cookieHeader(url: string): Promise<string> {
    return this.jar.getCookieString(url);
  }

  /** Set-Cookie ヘッダーを取り込む */
  async setCookies(setCookies: string[] | string, url: string): Promise<void> {
    const list = Array.isArray(setCookies) ? setCookies : [setCookies];
    for (const c of list) {
      try {
        await this.jar.setCookie(c, url);
      } catch (e) {
        log.warn('Failed to set cookie:', c, e);
      }
    }
  }

  /** プレーンな name=value 形式で1件だけセット */
  async setCookieRaw(name: string, value: string, domain: string): Promise<void> {
    const cookieStr = `${name}=${value}; Domain=${domain}; Path=/; HttpOnly; Secure`;
    const url = `https://${domain.replace(/^\./, '')}/`;
    await this.jar.setCookie(cookieStr, url, { ignoreError: true });
  }

  /** 認証に必要な user_session が存在するか */
  async hasLoginCookie(): Promise<boolean> {
    const cookies = await this.jar.getCookies('https://www.nicovideo.jp/');
    return cookies.some((c) => c.key === NicoAuthCookieName.USER_SESSION);
  }

  /** すべての Cookie をクリア */
  async clear(): Promise<void> {
    this.jar = new CookieJar();
    if (fs.existsSync(this.filePath)) {
      fs.unlinkSync(this.filePath);
    }
  }

  /** tough-cookie の Jar を Netscape 形式 (yt-dlp が読める) に変換して返す */
  async exportNetscape(): Promise<string> {
    const serialized = await this.jar.serialize();
    const cookies = (serialized.cookies ?? []) as Array<Record<string, unknown>>;
    const lines = ['# Netscape HTTP Cookie File', '# Generated by NNDD-RE', ''];
    for (const c of cookies) {
      const domain = String(c['domain'] ?? '');
      if (!domain) continue;
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const cookiePath = String(c['path'] ?? '/');
      const secure = c['secure'] ? 'TRUE' : 'FALSE';
      const expiresRaw = c['expires'];
      let expires = 0;
      if (expiresRaw && expiresRaw !== 'Infinity') {
        const t = new Date(String(expiresRaw)).getTime();
        if (!isNaN(t)) expires = Math.floor(t / 1000);
      }
      const name = String(c['key'] ?? '');
      const value = String(c['value'] ?? '');
      lines.push(`${domain}\t${includeSubdomains}\t${cookiePath}\t${secure}\t${expires}\t${name}\t${value}`);
    }
    return lines.join('\n');
  }

  /** 内部の jar (高度な操作用) */
  get rawJar(): CookieJar {
    return this.jar;
  }
}
